### ISSUE TITLE
The error appears when run the ctc_decoder in the tlinux system

### ISSUE THREAD

**Issue by joewale** [Slyne/ctc_decoder#1]
Hi, Slyne, 

   `  I follow your example for wenet in the folder : runtime/server/x86_gpu. And I run the command:  tritonserver --model-repository=model_repo，The error appears when run the above command in the tlinux system, while successfully in ubuntu system.  What is the problem?  Looking forward to your reply, thank you!`

0315 02:18:17.627657 8077 pb_stub.cc:402] Failed to process the request(s) for model 'scoring_0_1', message: TypeError: ctc_beam_search_decoder_batch() takes no keyword arguments

**Comment by joewale** [comment]
Linux 0484488c97c7 5.4.32-1-tlinux4-0001 #1 SMP Tue Jul 21 14:24:37 CST 2020 x86_64 x86_64 x86_64 GNU/Linux

Linux version 5.4.32-1-tlinux4-0001 (root@3c7067f9a859) (gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)) #1 SMP Tue Jul 21 14:24:37 CST 2020

cmake version 3.18.2

Python 3.8.3

**Comment by joewale** [comment]
I use the docker to deploy, but use the docker images with tlinux as base docker image.

**Comment by joewale** [comment]
[ctc_decoder_install.log](https://github.com/Slyne/ctc_decoder/files/8337992/ctc_decoder_install.log)
 
Hi,  @Slyne , the log of installation is given above, please help to see if there is a problem in my installation.  Looking forward to your reply, thank you!

The error in tritonserver as follows

```
[I0324 02:36:09.087216 1526 pb_stub.cc:402] Failed to process the request(s) for model 'scoring_0_0', message: TypeError: ctc_beam_search_decoder_batch() takes no keyword arguments

At:
  /home/speech_asr_async_svr/model_repo/scoring/1/model.py(181): execute
```

**Comment by joewale** [comment]
H

> > [ctc_decoder_install.log](https://github.com/Slyne/ctc_decoder/files/8337992/ctc_decoder_install.log)
> > Hi, @Slyne , the log of installation is given above, please help to see if there is a problem in my installation. Looking forward to your reply, thank you!
> > The error in tritonserver as follows
> > ```
> > [I0324 02:36:09.087216 1526 pb_stub.cc:402] Failed to process the request(s) for model 'scoring_0_0', message: TypeError: ctc_beam_search_decoder_batch() takes no keyword arguments
> > 
> > At:
> >   /home/speech_asr_async_svr/model_repo/scoring/1/model.py(181): execute
> > ```
> 
> Is it possible to share the Dockerfile ?

Hi, @Slyne . Is it possible to contact with wechat? my wechat: joewale

**Comment by Slyne** [comment]
Remove
```
blank_id=
space_id=
...
```
in model.py  will solve this issue.

Confirmed with @joewale

**Comment by joewale** [comment]
Thanks very much!
