### ISSUE TITLE
Wrong number or type of arguments for overload function 'map_batch'

### ISSUE THREAD

**Issue by Ryuk17** [Slyne/ctc_decoder#5]
报错定位到Wenet recognize_onnx.py的191行
![image](https://user-images.githubusercontent.com/22525811/171366881-45e51cdc-e145-453f-860a-57865039181c.png)

错误如下
![image](https://user-images.githubusercontent.com/22525811/171367052-e91d03ed-65ef-4a91-9285-d378f4a0d577.png)

请问这个问题要怎么修改呢？

**Comment by Ryuk17** [comment]
因为最新转onnx模型和recognize_onnx.py不一致，我使用的是这个版本
![image](https://user-images.githubusercontent.com/22525811/171367294-dcc9d4ae-7724-4c28-bd36-12504a7b3639.png)

**Comment by Slyne** [comment]
@Ryuk17  你可以用这个[脚本](https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/export_onnx_gpu.py)转onnx

map_batch的[参数定义](https://github.com/Slyne/ctc_decoder/blob/master/swig/ctc_beam_search_decoder.cpp#L181)
```
std::vector<std::string> map_batch(
    const std::vector<std::vector<int>> &batch_sents,
    const std::vector<std::string> &vocabulary, size_t num_processes,
    bool greedy, int blank_id)
```
你可以打印以下看看能不能对的上

另外191行不是这个吗? https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/recognize_onnx.py#L191

**Comment by Ryuk17** [comment]
感谢回复，我研究了下wenet那个recognize_onnx.py，我在这里加了一行代码，这样使用ctc_greedy_search就可以顺利运行了
![image](https://user-images.githubusercontent.com/22525811/171405564-a75bd0de-e9b4-4821-870e-94c0862ed587.png)

**Comment by Ryuk17** [comment]
不对诶，我得到了ctc_log_probs这个矩阵，它的大小是[T，C]（T是时间长度，C是字典大小），那就应该可以进行greedy_search和prefix_beam_search。如果map_batch支持这两种解码方式，那就应该可以调用吧？

**Comment by Ryuk17** [comment]
懂了，问题已经解掉了，十分感谢您的回复！
